### ISSUE TITLE
Falta la sección 2 de la pagina principal de la pagina del blog. En esta se presenta rápidamente los dos tipos de posts que se ofrecen en el blog: "Provoking thinking" y "Takeaways".

### ISSUE THREAD

**Issue by dpuerto** [macrowise/blog#10]

**Comment by dpuerto** [comment]
![captura de pantalla 2019-02-19 a las 9 49 27 a m](https://user-images.githubusercontent.com/44245994/53023669-ab148e80-342b-11e9-8a33-5f13c462dedd.png)

**Comment by ddazal** [comment]
Omitted by content redundancy
