### ISSUE TITLE
Como usuario quiero leer la explicación de la sección "Takeaways" de la pagina principal del blog

### ISSUE THREAD

**Issue by dpuerto** [macrowise/blog#12]
Utilizar el mismo texto que aparece en la sección 2 -Esta sección presenta rápidamente lo que son takeaways y editoriales.

**Comment by dpuerto** [comment]
![captura de pantalla 2019-02-19 a las 9 47 23 a m](https://user-images.githubusercontent.com/44245994/53023508-62f56c00-342b-11e9-8c0e-c210c277959e.png)

**Comment by dpuerto** [comment]
![captura de pantalla 2019-02-19 a las 9 48 24 a m](https://user-images.githubusercontent.com/44245994/53023595-891b0c00-342b-11e9-9d3f-6b65c45c4c4f.png)

**Comment by ddazal** [comment]
Omitted by content redundancy
