### ISSUE TITLE
Como usuario quiero ver la sección "Books" de los posts tipo "Provoking Thinking" que me ofrece Macrowise 

### ISSUE THREAD

**Issue by dpuerto** [macrowise/blog#24]

**Comment by dpuerto** [comment]
![captura de pantalla 2019-02-19 a las 9 22 56 a m](https://user-images.githubusercontent.com/44245994/53022272-d6e24500-3428-11e9-8f4a-6484a4d0526c.png)

**Comment by ddazal** [comment]
Already implemented
