### ISSUE TITLE
Como usuario quiero ver la sección "Videos" de los posts tipo "Provoking Thinking" que me ofrece Macrowise 

### ISSUE THREAD

**Issue by dpuerto** [macrowise/blog#25]

**Comment by dpuerto** [comment]
![captura de pantalla 2019-02-19 a las 9 22 56 a m](https://user-images.githubusercontent.com/44245994/53022244-c3cf7500-3428-11e9-8a72-fa9a1a4ceae2.png)

**Comment by ddazal** [comment]
Already implemented
