### ISSUE TITLE
Como usuario quiero leer la explicación del contenido que se presenta en la sección Provoking Thinking

### ISSUE THREAD

**Issue by dpuerto** [macrowise/blog#7]
Se debe utilizar el mismo texto que aparece en la sección 2 -sección que presenta Takeaways y Editorial - en el diseño de Mariana

**Comment by dpuerto** [comment]
![captura de pantalla 2019-02-19 a las 9 50 25 a m](https://user-images.githubusercontent.com/44245994/53023752-d1d2c500-342b-11e9-8ff7-69a46f2c0cc7.png)

**Comment by dpuerto** [comment]
![captura de pantalla 2019-02-19 a las 9 50 55 a m](https://user-images.githubusercontent.com/44245994/53023787-deefb400-342b-11e9-8bc5-a6146b98c3bb.png)

**Comment by ddazal** [comment]
Omitted by content redundancy
